export const translations = {
    pt: {
        title: "COPA DO MUNDO FIFA 2026",
        subtitle: "Resultados oficiais da ESPN, simulações em tempo real e chaveamento automático em português-BR.",
        loadingTable: "Carregando tabela oficial...",
        tabGroups: "Fase de Grupos",
        tabKnockout: "Mata-mata",
        filterLabel: "Visualizar grupo",
        filterAll: "Todos os grupos (A ao L)",
        groupInfo: "Os 2 melhores de cada grupo e os 8 melhores 3º colocados avançam automaticamente.",
        tablePos: "Pos",
        tableTeam: "Seleção",
        tablePts: "P",
        tablePl: "J",
        tableGd: "SG",
        tableGf: "GP",
        groupTitle: "Grupo",
        liveClass: "Atualização ao vivo",
        fixturesTitle: "Calendário e placares da fase de grupos",
        fixturesCount: "72 PARTIDAS",
        tableMatch: "Jogo",
        tableDateTime: "Data / Hora (BRT)",
        tableGroup: "Grupo",
        tableVs: "Confronto e placar",
        tableStadium: "Estádio / Sede",
        championTitle: "🏆 Campeão do Mundo 🏆",
        championSubtitle: "VENCEDOR DA COPA DO MUNDO FIFA 2026",
        confrontation: "JOGO",
        penalties: "Pênaltis:",
        tbd: "A definir",
        winnerOf: "Vencedor #",
        loserOf: "Perdedor #",
        thirdPlaceTitle: "Disputa do 3º Lugar",
        finalTitle: "Final",
        contribPix: "Contribuir via PIX",
        pixCopied: "Chave PIX copiada! Finalize no app do seu banco. Obrigado pelo apoio! 🏆",
        resetPredictions: "🗑️ Resetar palpites",
        resetConfirm: "Tem certeza que deseja resetar todos os palpites salvos?",
        resetDone: "Palpites resetados com sucesso.",
        round32: "16-avos de final",
        round16: "Oitavas de final",
        quarterFinals: "Quartas de final",
        semiFinals: "Semifinais",
        thirdPlace: "Disputa do 3º lugar",
        final: "Final",
        knockoutViewLabel: "Modo de visualização do mata-mata",
        knockoutBracketMode: "Chave",
        knockoutListMode: "Lista",
        fifaBadgeText: "FIFA",
        bracketR32: "16A",
        bracketR16: "OIT",
        bracketQF: "QF",
        bracketSF: "SF",
        officialBadge: "Oficial ESPN",
        editableBadge: "Palpite",
        officialStatusLive: "Resultados oficiais ESPN",
        officialStatusFallback: "Último snapshot válido",
        officialStatusUnavailable: "Sem atualização oficial",
        officialStatusReady: "Dados normalizados e prontos para exibição.",
        officialStatusCached: "Exibindo fallback local seguro enquanto a ESPN está indisponível.",
        officialStatusEmpty: "Resultados oficiais ainda não foram publicados para este momento."
    }
};

export const translateTeam = (name) => name;

export const translatePlaceholder = (text) => text;
