export const translations = {
    pt: {
        brandTitle: "WC26 Table",
        title: "COPA DO MUNDO FIFA 2026",
        brandSubtitle: "Copa do Mundo FIFA 2026",
        subtitle: "Resultados oficiais da ESPN, simulações em tempo real e chaveamento automático em português-BR.",
        loadingTable: "Carregando tabela oficial...",
        tabGroups: "Fase de Grupos",
        tabGroupsShort: "Grupos",
        tabKnockout: "Mata-mata",
        tabKnockoutShort: "Mata-mata",
        tabBracketShort: "Chave",
        tabCalendar: "Calendário",
        tabTodayShort: "Hoje",
        tabPredictions: "Meus Palpites",
        tabPredictionsShort: "Palpites",
        calendarSub: "Todos os jogos da copa em ordem cronológica. Filtre por status.",
        predictionsSub: "Resumo dos placares que você preencheu. Oficiais da ESPN ficam travados.",
        filterLabel: "Grupo",
        filterAll: "Todos os grupos (A ao L)",
        filterAllShort: "Todos (A–L)",
        groupInfo: "Os 2 melhores de cada grupo + os 8 melhores 3º colocados avançam.",
        tablePos: "Pos",
        tableTeam: "Seleção",
        tablePts: "P",
        tablePl: "J",
        tableGd: "SG",
        tableGf: "GP",
        groupTitle: "Grupo",
        liveClass: "Atualização ao vivo",
        fixturesTitle: "Jogos da fase de grupos",
        fixturesCount: "72 PARTIDAS",
        tableMatch: "Jogo",
        tableDateTime: "Data / Hora (BRT)",
        tableGroup: "Grupo",
        tableVs: "Confronto e placar",
        tableStadium: "Estádio / Sede",
        championTitle: "🏆 Campeão do Mundo 🏆",
        championSubtitle: "VENCEDOR DA COPA DO MUNDO FIFA 2026",
        confrontation: "JOGO",
        penalties: "Pênaltis:",
        tbd: "A definir",
        winnerOf: "Vencedor #",
        loserOf: "Perdedor #",
        thirdPlaceTitle: "Disputa do 3º Lugar",
        finalTitle: "Final",
        contribPix: "Contribuir via PIX",
        pixCopied: "Chave PIX copiada! Finalize no app do seu banco. Obrigado pelo apoio! 🏆",
        resetPredictions: "Resetar palpites",
        resetConfirm: "Tem certeza que deseja resetar todos os palpites salvos?",
        resetDone: "Palpites resetados com sucesso.",
        round32: "16-avos de final",
        round16: "Oitavas de final",
        quarterFinals: "Quartas de final",
        semiFinals: "Semifinais",
        thirdPlace: "Disputa do 3º lugar",
        final: "Final",
        knockoutViewLabel: "Modo de visualização do mata-mata",
        knockoutBracketMode: "Chave",
        knockoutListMode: "Lista",
        knockoutPhasePickerLabel: "Fases do mata-mata",
        knockoutPhaseHint: "Toque em uma fase para focar os jogos — no estilo Apple Sports.",
        fifaBadgeText: "FIFA",
        bracketR32: "16A",
        bracketR16: "OIT",
        bracketQF: "QF",
        bracketSF: "SF",
        officialBadge: "Oficial ESPN",
        editableBadge: "Palpite",
        officialStatusLive: "LIVE · ESPN",
        officialStatusFallback: "CACHE · ESPN",
        officialStatusUnavailable: "OFFLINE",
        officialStatusReady: "Dados normalizados e prontos para exibição.",
        officialStatusCached: "Exibindo fallback local seguro enquanto a ESPN está indisponível.",
        officialStatusEmpty: "Resultados oficiais ainda não foram publicados para este momento.",
        officialStatusSnapshotPrefix: "Snapshot de",
        officialStatusDroppedEntries: "registro(s) inválido(s) foram ignorados com segurança.",
        legendTitle: "Legenda",
        legendQualified: "1º–2º classificados",
        legendThird: "3º disputa vaga",
        legendOut: "4º eliminado",
        themeLight: "Modo Claro",
        themeDark: "Modo Escuro",
        nextMatchTitle: "Próximo jogo do dia",
        lastMatchTitle: "Jogo em destaque",
        upcomingTitle: "A seguir",
        noUpcoming: "Nenhum jogo pendente",
        statFilled: "Preenchidos",
        statCoverage: "Cobertura",
        statOfficial: "Oficiais ESPN",
        statYours: "Só palpites",
        noPredictions: "Você ainda não registrou palpites. Preencha placares nos jogos da fase de grupos."
    }
};

export const translateTeam = (name) => name;

export const translatePlaceholder = (text) => text;
